targets:
  $default:
    builders:
      json_serializable:
        enabled: false
      drift_dev:
        enabled: false
  test:
    sources:
      include:
        - test/**
    builders:
      json_serializable:
        enabled: true
        generate_for:
          - test/utils/serializable.dart
      drift_dev:
        enabled: true