targets:
  $default:
    builders:
      json_serializable:
        enabled: false
  test:
    sources:
      include:
        - test/**
    builders:
      json_serializable:
        enabled: true
        generate_for:
          - test/utils/serializable.dart
      drift_dev:
        options:
          sqlite:
            enabled: true
          postgres:
            enabled: true
          sql:
            dialects:
              - sqlite
              - postgres