name: drift_crdt
description: A Flutter-only implementation of a drift CRDT database, based on the `sqlite_crdt` package and `sqflite`.
version: 1.0.0
repository: https://github.com/JanezStupar/drift_crdt.git
homepage: https://janezstupar.com
issue_tracker: https://github.com/JanezStupar/drift_crdt/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.13.0
  sqflite: ^2.1.0
  path: ^1.8.0
  flutter:
    sdk: flutter
  synchroflite: ^0.1.0
  json_serializable: ^6.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  drift_testcases:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/integration_tests/drift_testcases
  sqflite_common_ffi: ^2.2.5
  test: ^1.22.0
  build_runner: ^2.4.5

flutter:
  assets:
    - test_asset.db
    - test_asset_migration.db

dependency_overrides:
  # Flutter's test packages don't support the latest analyzer yet.
  test_api: 0.6.1
