name: drift_crdt
description: A Flutter-only implementation of a drift CRDT database, based on the `sqlite_crdt` package and `sqflite`.
version: 1.1.0
repository: https://github.com/JanezStupar/drift_crdt.git
homepage: https://janezstupar.com
issue_tracker: https://github.com/JanezStupar/drift_crdt/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite_common: ^2.5.4+5
  drift: ^2.26.0
  drift_postgres: ^1.3.1
  sqlparser: ^0.41.0
  source_span: ^1.10.0
  sqflite: ^2.1.0
  path: ^1.8.0
  flutter:
    sdk: flutter
  sql_crdt: ^4.0.0
  sqlite_crdt: ^4.0.0
  postgres_crdt: ^4.0.0
  json_annotation: ^4.9.0
  postgres: ^3.5.7
  collection: ^1.19.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  drift_testcases:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/integration_tests/drift_testcases
  sqflite_common_ffi: ^2.2.5
  test: ^1.22.0
  build_runner: ^2.4.5
  json_serializable: ^6.2.0

dependency_overrides:
  sql_crdt:
    git:
      url: https://github.com/JanezStupar/sql_crdt.git
      ref: feature/postgres_related

  sqlite_crdt:
    git:
      url: https://github.com/JanezStupar/sqlite_crdt.git
      ref: feature/ver4

  postgres_crdt:
    git:
      url: https://github.com/JanezStupar/postgres_crdt.git
      ref: feature/ver4

platforms:
  linux:
  windows:
  macos:
  android:
  ios:

flutter:
  assets:
    - test_asset.db
    - test_asset_migration.db
